#!/bin/bash
# find the file offset of a symbol in a ELF file

ADDR=$(nm $1 | awk "/$2/ { print \$1 }")
objdump -s -F --start-address=0x$ADDR $1  |
awk '/Starting at file offset/ { sub(/)/, ""); print $9 ; exit(0); }'

